# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swf-DFP-TableView-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swf-DFP-TableView-demo
  pod 'Google-Mobile-Ads-SDK'

  target 'swf-DFP-TableView-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
